name: Issue Template
description: template for brief issue creation
title: "New Issue"
body:
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Tell us about this issue
      placeholder: Briefly explain about the issue. Also mention if it is a new issue or a bug.
    validations:
      required: true
  - type: textarea
    id: Tech-Stack
    attributes:
      label: Tech Stack
      description: Tell us about the tech stack you are going to use to solve this issue.
    validations:
      required: true
  - type: textarea
    id: Reference
    attributes:
      label: Reference
      description: Please mention reference if any.
   
  - type: checkboxes
    id: terms
    attributes:
      label: Are you creating this issue for yoursefl
      options:
        - label: "Yes"
        - label: "No"
    validations:
      requried: true
